// ABIs mínimos para interactuar con los contratos ENKI desde el frontend.
// Sólo se incluyen las funciones y eventos que la UI necesita.

export const GAME_ABI = [
  // ── Reads ────────────────────────────────────────────────────────────────────
  { name: 'hasJoined',       type: 'function', stateMutability: 'view',
    inputs:  [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'bool'    }] },
  { name: 'currentQuestionId', type: 'function', stateMutability: 'view',
    inputs:  [],
    outputs: [{ name: '', type: 'uint256' }] },
  { name: 'isFinished',      type: 'function', stateMutability: 'view',
    inputs:  [],
    outputs: [{ name: '', type: 'bool'    }] },
  { name: 'entryFee',        type: 'function', stateMutability: 'view',
    inputs:  [],
    outputs: [{ name: '', type: 'uint256' }] },
  { name: 'passingScore',    type: 'function', stateMutability: 'view',
    inputs:  [],
    outputs: [{ name: '', type: 'uint256' }] },
  { name: 'totalQuestions',  type: 'function', stateMutability: 'view',
    inputs:  [],
    outputs: [{ name: '', type: 'uint256' }] },
  { name: 'prizePool',       type: 'function', stateMutability: 'view',
    inputs:  [],
    outputs: [{ name: '', type: 'uint256' }] },
  { name: 'prizesCalculated', type: 'function', stateMutability: 'view',
    inputs:  [],
    outputs: [{ name: '', type: 'bool'    }] },
  { name: 'scores',          type: 'function', stateMutability: 'view',
    inputs:  [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }] },
  { name: 'hasClaimed',      type: 'function', stateMutability: 'view',
    inputs:  [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'bool'    }] },
  { name: 'hasPrizeClaimed', type: 'function', stateMutability: 'view',
    inputs:  [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'bool'    }] },
  { name: 'professor',       type: 'function', stateMutability: 'view',
    inputs:  [],
    outputs: [{ name: '', type: 'address' }] },
  { name: 'listaDeRondas',   type: 'function', stateMutability: 'view',
    inputs:  [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'hashVerificacionPregunta', type: 'bytes32' },
      { name: 'hashRespuestaCorrecta',    type: 'bytes32' },
      { name: 'commitPhaseOpen',          type: 'bool'    },
      { name: 'revealPhaseOpen',          type: 'bool'    },
    ] },
  // ── Writes ───────────────────────────────────────────────────────────────────
  { name: 'joinGame',        type: 'function', stateMutability: 'payable',
    inputs: [], outputs: [] },
  { name: 'commitAnswer',    type: 'function', stateMutability: 'nonpayable',
    inputs: [{ name: '_commitHash', type: 'bytes32' }], outputs: [] },
  { name: 'revealAnswer',    type: 'function', stateMutability: 'nonpayable',
    inputs: [
      { name: '_questionId', type: 'uint256' },
      { name: '_option',     type: 'uint8'   },
      { name: '_salt',       type: 'string'  },
    ], outputs: [] },
  { name: 'calculatePrizes', type: 'function', stateMutability: 'nonpayable',
    inputs: [], outputs: [] },
  { name: 'claimPrize',      type: 'function', stateMutability: 'nonpayable',
    inputs: [], outputs: [] },
  { name: 'claimDiploma',    type: 'function', stateMutability: 'nonpayable',
    inputs: [], outputs: [] },
  // ── Events ───────────────────────────────────────────────────────────────────
  { name: 'QuestionRevealed', type: 'event',
    inputs: [
      { name: 'questionId', type: 'uint256',   indexed: true  },
      { name: 'enunciado',  type: 'string',    indexed: false },
      { name: 'opciones',   type: 'string[4]', indexed: false },
    ] },
] as const

export const FACTORY_ABI = [
  { name: 'creationFee',   type: 'function', stateMutability: 'view',
    inputs:  [],
    outputs: [{ name: '', type: 'uint256' }] },
  { name: 'getGamesCount', type: 'function', stateMutability: 'view',
    inputs:  [],
    outputs: [{ name: '', type: 'uint256' }] },
  { name: 'games',         type: 'function', stateMutability: 'view',
    inputs:  [{ name: '', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }] },
] as const
